application: penadepina
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /pgdocs/
  static_dir: pgdocs
- url: /pgdoc/.*
  script: docsearch/main.py
- url: .*
  script: myplanet.py

